import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'kashmiri-pashmina-shawl',
    name: 'Kashmiri Pashmina Shawl',
    description: 'A luxurious handwoven pashmina shawl, embodying the timeless elegance of Kashmiri craftsmanship. Perfect for cool evenings.',
    price: 250,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Autumn/Winter',
    sizes: ['One Size'],
    condition: 'New',
    origin: 'Kashmir, India',
  },
  {
    id: '2',
    slug: 'vintage-denim-jacket',
    name: 'Vintage Denim Jacket',
    description: 'A classic denim jacket with a unique vintage wash and relaxed fit. A wardrobe staple that tells a story.',
    price: 85,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Outerwear',
    gender: 'Women',
    season: 'Spring/Summer',
    sizes: ['S', 'M', 'L'],
    condition: 'Pre-loved',
    origin: 'USA',
  },
  {
    id: '3',
    slug: 'linen-trousers-olive',
    name: 'Linen Trousers - Olive',
    description: 'Breathable and stylish linen trousers in a versatile olive green. Ideal for warm weather and casual outings.',
    price: 70,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Bottoms',
    gender: 'Men',
    season: 'Spring/Summer',
    sizes: ['M', 'L', 'XL'],
    condition: 'New',
    origin: 'Portugal',
  },
  {
    id: '4',
    slug: 'silk-button-up-shirt',
    name: 'Silk Button-Up Shirt',
    description: 'An elegant and soft silk shirt with a fluid drape. Can be dressed up or down for any occasion.',
    price: 120,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Tops',
    gender: 'Women',
    season: 'Autumn/Winter',
    sizes: ['S', 'M'],
    condition: 'New',
    origin: 'China',
  },
  {
    id: '5',
    slug: 'wool-crewneck-sweater',
    name: 'Wool Crewneck Sweater',
    description: 'A cozy and warm wool sweater in a rich walnut brown. Perfect for layering during colder months.',
    price: 95,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Tops',
    gender: 'Unisex',
    season: 'Autumn/Winter',
    sizes: ['S', 'M', 'L', 'XL'],
    condition: 'Pre-loved',
    origin: 'Scotland',
  },
  {
    id: '6',
    slug: 'leather-tote-bag',
    name: 'Leather Tote Bag',
    description: 'A durable and spacious leather tote bag, handcrafted to last a lifetime. Features an internal pocket for essentials.',
    price: 180,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Spring/Summer',
    sizes: ['One Size'],
    condition: 'New',
    origin: 'Italy',
  },
   {
    id: '7',
    slug: 'corduroy-pants-brown',
    name: 'Corduroy Pants - Brown',
    description: 'Classic straight-leg corduroy pants in a deep brown hue. Soft, comfortable, and perfect for a relaxed yet stylish look.',
    price: 75,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Bottoms',
    gender: 'Men',
    season: 'Autumn/Winter',
    sizes: ['S', 'M', 'L'],
    condition: 'New',
    origin: 'Vietnam',
  },
  {
    id: '8',
    slug: 'cashmere-beanie-gray',
    name: 'Cashmere Beanie - Gray',
    description: 'A soft and luxurious cashmere beanie in a neutral gray. The perfect accessory to keep you warm and stylish.',
    price: 60,
    images: ['https://placehold.co/800x1000', 'https://placehold.co/800x1000'],
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Autumn/Winter',
    sizes: ['One Size'],
    condition: 'New',
    origin: 'Mongolia',
  },
];
